[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:kafka]
command=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
autorestart=true
priority=10
stdout_logfile=/var/log/kafka.log
stderr_logfile=/var/log/kafka.log

[program:ingester]
command=node /app/ingester/dist/index.js
autorestart=true
priority=30
environment=KAFKA_BROKERS="localhost:9092",KAFKA_TOPIC_TRADES="crypto-trades"
stdout_logfile=/var/log/ingester.log
stderr_logfile=/var/log/ingester.log

[program:processor]
command=node /app/processor/dist/index.js
autorestart=true
priority=30
environment=KAFKA_BROKERS="localhost:9092",KAFKA_TOPIC_TRADES="crypto-trades",KAFKA_TOPIC_METRICS="crypto-metrics",SMA_WINDOW="20",ANOMALY_ZSCORE_THRESHOLD="2.5"
stdout_logfile=/var/log/processor.log
stderr_logfile=/var/log/processor.log

[program:api]
command=node /app/api/dist/index.js
autorestart=true
priority=30
environment=KAFKA_BROKERS="localhost:9092",KAFKA_TOPIC_METRICS="crypto-metrics",API_PORT="3001"
stdout_logfile=/var/log/api.log
stderr_logfile=/var/log/api.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=20
stdout_logfile=/var/log/nginx-access.log
stderr_logfile=/var/log/nginx-error.log
